// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxsxtmsnxbfrbeguifmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4c3h0bXNueGJmcmJlZ3VpZm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjA2MTQsImV4cCI6MjA1ODIzNjYxNH0.v2Dk9OnY9Gz5LeLwAwfPNdio03VLXcMl7zUqPSIAflI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);